name: zarf
repository: github.com/willswire/trivy-plugin-zarf
version: 0.1.0
summary: Scan Zarf packages for vulnerabilities
usage: zarf <zarf-package.tar>
description: A Trivy plugin for scanning Zarf packages containing OCI images
platforms:
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/willswire/trivy-plugin-zarf/releases/download/v0.1.0/trivy-plugin-zarf_0.1.0_darwin_amd64.tar.gz
    bin: ./zarf
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/willswire/trivy-plugin-zarf/releases/download/v0.1.0/trivy-plugin-zarf_0.1.0_darwin_arm64.tar.gz
    bin: ./zarf
  - selector:
      os: linux
      arch: amd64
    uri: https://github.com/willswire/trivy-plugin-zarf/releases/download/v0.1.0/trivy-plugin-zarf_0.1.0_linux_amd64.tar.gz
    bin: ./zarf
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/willswire/trivy-plugin-zarf/releases/download/v0.1.0/trivy-plugin-zarf_0.1.0_linux_arm64.tar.gz
    bin: ./zarf
requirements:
  - name: zarf
    kind: executable
    version: '>= 0.24.0'
  - name: trivy
    kind: executable
    version: '>= 0.41.0'
