# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Setup Zarf
      uses: zarf-dev/setup-zarf@v1.0.1

    - name: Setup Trivy
      uses: aquasecurity/setup-trivy@v0.2.2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -tags=integration -v ./...

